### ISSUE TITLE
Appear to stop being able to send

### ISSUE THREAD

**Issue by anthonyvercolano** [amqp/rhea#171] opened 2018-12-17 21:05 UTC
In the Azure IOT SDK, we have some code to send data to the cloud.

Essentially we place data into a queue and call into a state machine that is controlling the sender link.

The sending code in the state machine has a while loop:
```
          send: () => {
            while ((this._unsentMessageQueue.length > 0) && this._rheaSender.sendable()) {
              debug('unsent message queue length is: ' + this._unsentMessageQueue.length);
              /*Codes_SRS_NODE_AMQP_SENDER_LINK_16_020: [When the link gets attached, the messages shall be sent in the order they were queued.] */
 ```
An application utilizing the SDK is sending a message about 1/second.  Occasionally, it encounters a problem, which from the debug logs would suggest that this._rheaSender.sendable() is returning false.

The application developer placed an additional debug into the session.js:46 code
```
CircularBuffer.prototype.available = function () {
    console.log("AZURE DEBUGINFO: capacity: " + this.capacity + " size:" + this.size + ' head=' + this.head + ' tail=' + this.tail + " available:" + (this.capacity - this.size));
    return this.capacity - this.size;
};
```

He sent the following:
Ok... this looks interesting
(note the "AZURE DEBUGINFO" from the CircularBuffer.prototype.available call)
```
mSB: DEBUG: [azureIoTEventHub1]=>Event submitted to Azure IoT Hub                                                
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:14.636Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:15.019Z azure-iot-device-amqp:Amqp using existing d2c link                                      
2018-12-17T18:31:15.019Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.           
AZURE DEBUGINFO: capacity: 2048 size:2044 head=1 tail=2045 available:4                                           
2018-12-17T18:31:15.021Z azure-iot-amqp-base:SenderLink unsent message queue length is: 1                        
2018-12-17T18:31:15.022Z azure-iot-amqp-base:SenderLink message placed in dictionary for lookup later.           
mSB: DEBUG: [azureIoTEventHub1]=>Event submitted to Azure IoT Hub                                                
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:15.432Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:15.520Z azure-iot-device-amqp:Amqp using existing d2c link                                      
2018-12-17T18:31:15.521Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.           
AZURE DEBUGINFO: capacity: 2048 size:2045 head=1 tail=2046 available:3                                           
2018-12-17T18:31:15.522Z azure-iot-amqp-base:SenderLink unsent message queue length is: 1                        
2018-12-17T18:31:15.523Z azure-iot-amqp-base:SenderLink message placed in dictionary for lookup later.           
mSB: DEBUG: [azureIoTEventHub1]=>Event submitted to Azure IoT Hub                                                
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:15.641Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:16.026Z azure-iot-device-amqp:Amqp using existing d2c link                                      
2018-12-17T18:31:16.026Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.           
AZURE DEBUGINFO: capacity: 2048 size:2046 head=1 tail=2047 available:2                                           
2018-12-17T18:31:16.027Z azure-iot-amqp-base:SenderLink unsent message queue length is: 1                        
2018-12-17T18:31:16.028Z azure-iot-amqp-base:SenderLink message placed in dictionary for lookup later.           
mSB: DEBUG: [azureIoTEventHub1]=>Event submitted to Azure IoT Hub                                                
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:16.143Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:16.528Z azure-iot-device-amqp:Amqp using existing d2c link                                      
2018-12-17T18:31:16.531Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.           
AZURE DEBUGINFO: capacity: 2048 size:2047 head=1 tail=0 available:1                                              
2018-12-17T18:31:16.533Z azure-iot-amqp-base:SenderLink unsent message queue length is: 1                        
2018-12-17T18:31:16.535Z azure-iot-amqp-base:SenderLink message placed in dictionary for lookup later.           
mSB: DEBUG: [azureIoTEventHub1]=>Event submitted to Azure IoT Hub                                                
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:16.647Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_
AZURE DEBUGINFO: capacity: 2048 size:5 head=2 tail=7 available:2043                                              
2018-12-17T18:31:17.035Z azure-iot-device-amqp:Amqp using existing d2c link                                      
2018-12-17T18:31:17.035Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.           
AZURE DEBUGINFO: capacity: 2048 size:2048 head=1 tail=1 available:0
```                                           
Please notice that the CircularBuffer.prototype.available is called three times per deviceClient.sendEvent (Azure Device SDK). One of the three is constantly decreasing until the point it's "0" and becomes unavailable. Hence stop transmitting messages. 5-10 later the device twin becomes "Disconnected".

I started the device at 06:00 and the error happened at 18:31:17.

I've noted in my own testing around this that the call that is to the CircularBuffer.available that is constantly decreasing seems to be when I call this._rheaSender.sendable().

Any thoughts on this?

**Comment by grs** [comment] 2018-12-17 21:22
Messages are removed from the outgoing buffer when settled by the receiving process. Is it possible the messages are not being accepted?

**Comment by anthonyvercolano** [comment] 2018-12-17 22:11
Here is a typical sender flow.  It certainly appears as though it has been settled by the other end of the send link.

```
2018-12-17T20:30:51.224Z azure-iot-device-amqp:Amqp using existing d2c link
2018-12-17T20:30:51.224Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.
AZURE DEBUGINFO: capacity: 2048 size:3 head=1 tail=4 available:2045
2018-12-17T20:30:51.224Z azure-iot-amqp-base:SenderLink unsent message queue length is: 1
2018-12-17T20:30:51.225Z rhea:message Encoding section 1 of 4: Typed { type: TypeDesc { name: 'List0', typecode: 69, width: 0, category: 1, create: { [Function] typecode: 69 } }, value: [], descriptor: { [Number: 112] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 112 } }
2018-12-17T20:30:51.225Z rhea:message Encoding section 2 of 4: Typed { type: TypeDesc { name: 'List32', typecode: 208, width: 4, category: 3, create: { [Function] typecode: 208 } }, value: [ <2 empty items>, Typed { type: [Object], value: '/devices/1111toercola/messages/events' } ], descriptor: { [Number: 115] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 115 } }
2018-12-17T20:30:51.225Z rhea:message Encoding section 3 of 4: Typed { type: TypeDesc { name: 'Map32', typecode: 209, width: 4, category: 3, create: { [Function] typecode: 209 } }, value: [ Typed { type: [Object], value: 'someProperty' }, { [Number: 2] type: [Object], value: 2 } ], descriptor: { [Number: 116] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 116 } }
2018-12-17T20:30:51.226Z rhea:message Encoding section 4 of 4: Typed { type: TypeDesc { name: 'Vbin8', typecode: 160, width: 1, category: 2, create: { [Function] typecode: 160 } }, value: <Buffer 7b 22 74 69 6d 65 53 74 61 6d 70 22 3a 22 32 30 31 38 2d 31 32 2d 31 37 54 32 30 3a 33 30 3a 35 31 2e 32 32 34 5a 22 2c 22 6d 73 67 43 6f 75 6e 74 22 ... >, descriptor: { [Number: 117] type: TypeDesc { name: 'SmallUlong', typecode: 83, width: 1, category: 1, read: [Function: read], write: [Function: write], create: [Object] }, value: 117 } }
2018-12-17T20:30:51.226Z rhea:message encoded 143 bytes
2018-12-17T20:30:51.226Z azure-iot-amqp-base:SenderLink message placed in dictionary for lookup later.
2018-12-17T20:30:51.226Z rhea:frames [connection-1]:0 -> transfer#14 {"handle":4,"delivery_id":4,"delivery_tag":{"type":"Buffer","data":[49]}} <Buffer 00 53 70 45 00 53 73 d0 00 00 00 2d 00 00 00 03 40 40 a1 25 2f 64 65 76 69 63 65 73 2f 31 31 31 31 74 6f 65 72 63 6f 6c 61 2f 6d 65 73 73 61 67 65 73 ... >
2018-12-17T20:30:51.226Z rhea:raw [connection-1] SENT: 173 000000ad02000000005314d00000000e0000000652045204a0013143424200537045005373d00000002d000000034040a1252f646576696365732f31313131746f6572636f6c612f6d657373616765732f6576656e7473005374d10000001400000002a10c736f6d6550726f70657274795202005375a0357b2274696d655374616d70223a22323031382d31322d31375432303a33303a35312e3232345a222c226d7367436f756e74223a317d
AZURE DEBUGINFO: capacity: 2048 size:2 head=1 tail=3 available:2046
2018-12-17T20:30:51.314Z rhea:io [connection-1] read 24 bytes
2018-12-17T20:30:51.314Z rhea:io [connection-1] got frame of size 24
2018-12-17T20:30:51.314Z rhea:raw [connection-1] RECV: 24 0000001802000000005315c00b0641520440410053244540
2018-12-17T20:30:51.314Z rhea:frames [connection-1]:0 <- disposition#15 {"role":true,"first":4,"settled":true,"state":[]} 
2018-12-17T20:30:51.314Z rhea:events [connection-1] Received disposition for outgoing transfers
2018-12-17T20:30:51.315Z rhea:events [connection-1] Link got event: accepted
2018-12-17T20:30:51.315Z azure-iot-amqp-base:SenderLink in sender attached state - accepted event for rheaSender_9732ea89-a381-40f8-be76-5321fb7e8f99
[32mSent message #[39m2
2018-12-17T20:30:51.315Z rhea:events [connection-1] Link got event: settled
2018-12-17T20:30:51.315Z rhea:events [connection-1] Session got event: settled
2018-12-17T20:30:51.315Z rhea:events [connection-1] Connection got event: settled
2018-12-17T20:30:51.315Z rhea:events [9796dfad-f812-2a42-8d82-badd6a9d2c55] Container got event: settled
AZURE DEBUGINFO: capacity: 2048 size:2 head=1 tail=3 available:2046
2018-12-17T20:30:52.240Z azure-iot-device-amqp:Amqp using existing d2c link
2018-12-17T20:30:52.240Z azure-iot-amqp-base:SenderLink placing a message in the unsent message queue.
AZURE DEBUGINFO: capacity: 2048 size:4 head=1 tail=5 available:2044
```
At least it looks like the disposition is saying it was settled.

Things are getting interesting though.  BEFORE setting up this sender link I set up a pair of links to work with something called device twins.  One sender link.  One receiver link.  The attaches look like this:

```
AZURE DEBUGINFO: capacity: 2048 size:0 head=1 tail=1 available:2048
2018-12-17T20:30:49.213Z rhea:frames [connection-1]:0 -> attach#12 {"name":"rheaSender_a943ffd2-bf6f-4869-a95a-f33e01bf14e5","handle":2,"snd_settle_mode":1,"source":[],"target":["/devices/1111toercola/twin"],"properties":{"com.microsoft:client-version":"azure-iot-device/1.8.2 (node v8.11.3; Windows_NT 10.0.17763; x64)","com.microsoft:channel-correlation-id":"twin:fb164f3a-e6eb-42b6-8714-107ca670dff8","com.microsoft:api-version":"2018-06-30"}} 
2018-12-17T20:30:49.213Z rhea:raw [connection-1] SENT: 352 0000016002000000005312d0000001500000000ea12f7268656153656e6465725f61393433666664322d626636662d343836392d613935612d6633336530316266313465355202425001500000532845005329d00000002000000001a11a2f646576696365732f31313131746f6572636f6c612f7477696e404043404040d1000000dd00000006a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea141617a7572652d696f742d6465766963652f312e382e3220286e6f64652076382e31312e333b2057696e646f77735f4e542031302e302e31373736333b2078363429a324636f6d2e6d6963726f736f66743a6368616e6e656c2d636f7272656c6174696f6e2d6964a1297477696e3a66623136346633612d653665622d343262362d383731342d313037636136373064666638a319636f6d2e6d6963726f736f66743a6170692d76657273696f6ea10a323031382d30362d3330
2018-12-17T20:30:49.320Z rhea:io [connection-1] read 367 bytes
2018-12-17T20:30:49.320Z rhea:io [connection-1] got frame of size 367
2018-12-17T20:30:49.320Z rhea:raw [connection-1] RECV: 367 0000016f02000000005312d00000015f0000000ea12f7268656153656e6465725f61393433666664322d626636662d343836392d613935612d66333365303162663134653552024150015000005328c00c0b4040404040404040404040005329c02307a11a2f646576696365732f31313131746f6572636f6c612f7477696e4040404040404040408000000000001000004040c1da06a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea141617a7572652d696f742d6465766963652f312e382e3220286e6f64652076382e31312e333b2057696e646f77735f4e542031302e302e31373736333b2078363429a324636f6d2e6d6963726f736f66743a6368616e6e656c2d636f7272656c6174696f6e2d6964a1297477696e3a66623136346633612d653665622d343262362d383731342d313037636136373064666638a319636f6d2e6d6963726f736f66743a6170692d76657273696f6ea10a323031382d30362d3330
2018-12-17T20:30:49.320Z rhea:frames [connection-1]:0 <- attach#12 {"name":"rheaSender_a943ffd2-bf6f-4869-a95a-f33e01bf14e5","handle":2,"role":true,"snd_settle_mode":1,"source":[null,null,null,null,null,null,null,null,null,null,null],"target":["/devices/1111toercola/twin",null,null,null,null,null,null],"max_message_size":1048576,"properties":{"com.microsoft:client-version":"azure-iot-device/1.8.2 (node v8.11.3; Windows_NT 10.0.17763; x64)","com.microsoft:channel-correlation-id":"twin:fb164f3a-e6eb-42b6-8714-107ca670dff8","com.microsoft:api-version":"2018-06-30"}} 
2018-12-17T20:30:49.321Z rhea:events [connection-1] Link got event: sender_open
2018-12-17T20:30:49.321Z azure-iot-amqp-base:SenderLink attaching -> attached (action:attaching.senderOpenEvent)
2018-12-17T20:30:49.321Z azure-iot-amqp-base:SenderLink link attached. processing unsent message queue
2018-12-17T20:30:49.322Z azure-iot-amqp-base:Amqp creating receiver link for: /devices/1111toercola/twin
2018-12-17T20:30:49.322Z azure-iot-amqp-base:ReceiverLink detached -> attaching (action:detached.attach)
2018-12-17T20:30:49.322Z azure-iot-amqp-base:ReceiverLink attaching receiver name: rheaReceiver_5afde115-476b-4dcb-adce-660ddfd596d7 with address: /devices/1111toercola/twin
AZURE DEBUGINFO: capacity: 2048 size:0 head=1 tail=1 available:2048
2018-12-17T20:30:49.323Z rhea:frames [connection-1]:0 -> attach#12 {"name":"rheaReceiver_5afde115-476b-4dcb-adce-660ddfd596d7","handle":3,"role":true,"snd_settle_mode":1,"source":["/devices/1111toercola/twin"],"target":[],"properties":{"com.microsoft:client-version":"azure-iot-device/1.8.2 (node v8.11.3; Windows_NT 10.0.17763; x64)","com.microsoft:channel-correlation-id":"twin:fb164f3a-e6eb-42b6-8714-107ca670dff8","com.microsoft:api-version":"2018-06-30"}} 
2018-12-17T20:30:49.324Z rhea:raw [connection-1] SENT: 354 0000016202000000005312d0000001520000000ea1317268656152656365697665725f35616664653131352d343736622d346463622d616463652d36363064646664353936643752034150015000005328d00000002000000001a11a2f646576696365732f31313131746f6572636f6c612f7477696e00532945404040404040d1000000dd00000006a31c636f6d2e6d6963726f736f66743a636c69656e742d76657273696f6ea141617a7572652d696f742d6465766963652f312e382e3220286e6f64652076382e31312e333b2057696e646f77735f4e542031302e302e31373736333b2078363429a324636f6d2e6d6963726f736f66743a6368616e6e656c2d636f7272656c6174696f6e2d6964a1297477696e3a66623136346633612d653665622d343262362d383731342d313037636136373064666638a319636f6d2e6d6963726f736f66743a6170692d76657273696f6ea10a323031382d30362d3330
2018-12-17T20:30:49.324Z rhea:io [connection-1] read 40 bytes
2018-12-17T20:30:49.324Z rhea:io [connection-1] got frame of size 40
2018-12-17T20:30:49.324Z rhea:raw [connection-1] RECV: 40 0000002802000000005313c01b0b52017000001388520270000007fe52024370000003e843404240
2018-12-17T20:30:49.324Z rhea:frames [connection-1]:0 <- flow#13 {"next_incoming_id":1,"incoming_window":5000,"next_outgoing_id":2,"outgoing_window":2046,"handle":2,"link_credit":1000} 
2018-12-17T20:30:49.325Z rhea:events [connection-1] Link got event: sender_flow
2018-12-17T20:30:49.325Z rhea:events [connection-1] Session got event: sender_flow
2018-12-17T20:30:49.325Z rhea:events [connection-1] Connection got event: sender_flow
```

Note the snd_settle_mode in the attaches.

If I don't set up these two links, everything works fine.  The available count does NOT keep going down on each send.

However, except for a few operation on these "twin" links prior to even setting up the normal sending link that I am having trouble with, nothing is ever done with these twin links again.  Nothing.  So something about these two "twin" links really seems to affect the other sending link.

**Comment by grs** [comment] 2018-12-18 12:01
Yes, there was a bug with presettled messages. That should now be fixed by https://github.com/amqp/rhea/commit/dd053e67ab6886ccf53c800c071db842449d80ce

**Comment by wmmihaa** [comment] 2018-12-18 12:14
Brilliant. I’ll test it in a couple hours

**Comment by wmmihaa** [comment] 2018-12-18 14:05
I can confirm that the issue is resolved. All links keep a steady size. 

```Sent message #25
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=27 tail=27 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
Sent message #26
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=28 tail=28 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
Sent message #27
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=29 tail=29 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
Sent message #28
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=30 tail=30 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
Sent message #29
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=31 tail=31 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
Sent message #30
app.js:46
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:0 head=32 tail=32 available:2048
session.js:47
AZURE DEBUGINFO: capacity: 2048 size:1 head=1 tail=2 available:2047```

*When do you guys think this fix will be in released?*

**Comment by grs** [comment] 2018-12-18 14:41
Thanks for confirming! I have published a new release (0.3.6) with that fix in it now.

**Comment by wmmihaa** [comment] 2018-12-18 15:02
BTW... would you mind updating the major version (considering the package is stable). There are other packages (such as Microsoft Azure IoT) that dependes on this package with dependancies set to ^0.2.18, and because **rhea** does not have a stable version, **npm install** will not install latest minor version...

**Comment by grs** [comment] 2018-12-18 15:39
Not sure I understand. Are you saying that there are packages with rhea ^0.2.18 as a dependency? If so those dependency declarations would need to be updated I think.

**Comment by wmmihaa** [comment] 2018-12-18 15:45
What I mean is dependencies to rhea@^0.2.18 will install rhea@0.2.20 (not rhea@0.3.6) as this is not a public version.
If the version would have been stable (>=1.*.*):  rhea@^1.2.18 would have installed rhea@1.3.6

For non-public version (0.*.*), "^major.minor.patch" will only update patch, not minor (at least for npm 6.4.1)

**Comment by grs** [comment] 2018-12-18 15:52
Ok, understood, thanks for the explanation. I'n the very short term I think you still need tp update those deps right? I will however plan for a move to a 'stable' version number.

**Comment by wmmihaa** [comment] 2018-12-18 15:53
Short term yes...

**Closed** 2019-03-20 16:28 UTC
